services:
  - type: web
    name: text-analysis-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    repo: https://github.com/nicowaelti/makeathon_TeamNumber1.git
    branch: main
