services:
  - type: web
    name: flask-hello-world
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    repo: https://github.com/nicowaelti/makeathon_TeamNumber1.git
    branch: main
